export const DEFAULT_PERMISSIONS = [
  { key: "dashboard.read", module: "dashboard", action: "read", description: "View dashboard" },
  { key: "profile.read", module: "profile", action: "read", description: "View own profile" },
  { key: "profile.update", module: "profile", action: "update", description: "Update own profile" },
  { key: "company.read", module: "company", action: "read", description: "View company details" },
  { key: "users.read", module: "users", action: "read", description: "View users" },
  { key: "users.create", module: "users", action: "create", description: "Create users" },
  { key: "users.update", module: "users", action: "update", description: "Update users" },
  { key: "users.disable", module: "users", action: "disable", description: "Disable users" },
  { key: "roles.read", module: "roles", action: "read", description: "View roles" },
  { key: "roles.assign", module: "roles", action: "assign", description: "Assign roles" },
  { key: "roles.update", module: "roles", action: "update", description: "Update role permissions" },
  { key: "products.read", module: "products", action: "read", description: "View products" },
  { key: "products.create", module: "products", action: "create", description: "Create products" },
  { key: "products.update", module: "products", action: "update", description: "Update products" },
  { key: "products.delete", module: "products", action: "delete", description: "Archive products" },
  { key: "inventory.adjust", module: "inventory", action: "adjust", description: "Adjust stock quantity" },
  { key: "sales.read", module: "sales", action: "read", description: "View sales orders" },
  { key: "sales.create", module: "sales", action: "create", description: "Create sales orders" },
  { key: "sales.update", module: "sales", action: "update", description: "Update sales orders" },
  { key: "sales.confirm", module: "sales", action: "confirm", description: "Confirm sales orders" },
  { key: "sales.cancel", module: "sales", action: "cancel", description: "Cancel sales orders" },
  { key: "sales.quotations.read", module: "sales", action: "quotations.read", description: "View quotations" },
  { key: "sales.quotations.create", module: "sales", action: "quotations.create", description: "Create quotations" },
  { key: "sales.quotations.update", module: "sales", action: "quotations.update", description: "Update quotations" },
  { key: "sales.quotations.send", module: "sales", action: "quotations.send", description: "Send quotations" },
  { key: "sales.quotations.accept", module: "sales", action: "quotations.accept", description: "Accept quotations" },
  { key: "sales.quotations.reject", module: "sales", action: "quotations.reject", description: "Reject quotations" },
  { key: "sales.quotations.expire", module: "sales", action: "quotations.expire", description: "Expire quotations" },
  { key: "sales.quotations.convert", module: "sales", action: "quotations.convert", description: "Convert quotations to sales orders" },
  { key: "sales.invoices.read", module: "sales", action: "invoices.read", description: "View sales invoices" },
  { key: "sales.invoices.create", module: "sales", action: "invoices.create", description: "Create sales invoices" },
  { key: "sales.invoices.update", module: "sales", action: "invoices.update", description: "Update draft sales invoices" },
  { key: "sales.invoices.issue", module: "sales", action: "invoices.issue", description: "Issue sales invoices" },
  { key: "sales.invoices.cancel", module: "sales", action: "invoices.cancel", description: "Cancel sales invoices" },
  { key: "vendors.read", module: "vendors", action: "read", description: "View vendors" },
  { key: "vendors.create", module: "vendors", action: "create", description: "Create vendors" },
  { key: "vendors.update", module: "vendors", action: "update", description: "Update vendors" },
  { key: "purchases.read", module: "purchases", action: "read", description: "View purchase orders" },
  { key: "purchases.create", module: "purchases", action: "create", description: "Create purchase orders" },
  { key: "purchases.update", module: "purchases", action: "update", description: "Update purchase orders" },
  { key: "purchases.receive", module: "purchases", action: "receive", description: "Receive purchase orders" },
  { key: "purchases.cancel", module: "purchases", action: "cancel", description: "Cancel purchase orders" },
  { key: "finance.read", module: "finance", action: "read", description: "View finance records" },
  {
    key: "finance.accounts.create",
    module: "finance",
    action: "accounts.create",
    description: "Create finance accounts",
  },
  {
    key: "finance.accounts.update",
    module: "finance",
    action: "accounts.update",
    description: "Update finance accounts",
  },
  {
    key: "finance.journals.create",
    module: "finance",
    action: "journals.create",
    description: "Create journal entries",
  },
  {
    key: "finance.journals.update",
    module: "finance",
    action: "journals.update",
    description: "Update draft journal entries",
  },
  {
    key: "finance.journals.post",
    module: "finance",
    action: "journals.post",
    description: "Post journal entries",
  },
  {
    key: "finance.journals.cancel",
    module: "finance",
    action: "journals.cancel",
    description: "Cancel draft journal entries",
  },
  {
    key: "finance.receivables.update",
    module: "finance",
    action: "receivables.update",
    description: "Update receivables",
  },
  {
    key: "finance.payables.update",
    module: "finance",
    action: "payables.update",
    description: "Update payables",
  },
  {
    key: "finance.periods.read",
    module: "finance",
    action: "periods.read",
    description: "View finance periods",
  },
  {
    key: "finance.periods.manage",
    module: "finance",
    action: "periods.manage",
    description: "Create and manage finance periods",
  },
  {
    key: "finance.payments.read",
    module: "finance",
    action: "payments.read",
    description: "View receivable and payable payments",
  },
  {
    key: "finance.payments.create",
    module: "finance",
    action: "payments.create",
    description: "Create receivable and payable payments",
  },
  {
    key: "finance.reports.read",
    module: "finance",
    action: "reports.read",
    description: "View finance reports",
  },
  {
    key: "finance.journals.reverse",
    module: "finance",
    action: "journals.reverse",
    description: "Reverse posted journal entries",
  },
  { key: "crm.read", module: "crm", action: "read", description: "View CRM leads and customers" },
  { key: "crm.create", module: "crm", action: "create", description: "Create CRM leads and customers" },
  { key: "crm.update", module: "crm", action: "update", description: "Update CRM leads and customers" },
  { key: "crm.convert", module: "crm", action: "convert", description: "Convert leads to customers" },
  { key: "crm.archive", module: "crm", action: "archive", description: "Archive CRM leads and customers" },
  { key: "crm.deals.read", module: "crm", action: "deals.read", description: "View CRM deals" },
  { key: "crm.deals.create", module: "crm", action: "deals.create", description: "Create CRM deals" },
  { key: "crm.deals.update", module: "crm", action: "deals.update", description: "Update CRM deals" },
  { key: "crm.deals.close", module: "crm", action: "deals.close", description: "Close CRM deals as won or lost" },
  { key: "crm.tasks.read", module: "crm", action: "tasks.read", description: "View CRM sales tasks" },
  { key: "crm.tasks.create", module: "crm", action: "tasks.create", description: "Create CRM sales tasks" },
  { key: "crm.tasks.update", module: "crm", action: "tasks.update", description: "Update CRM sales tasks" },
  { key: "crm.pipeline.read", module: "crm", action: "pipeline.read", description: "View CRM pipeline stages" },
  { key: "crm.pipeline.update", module: "crm", action: "pipeline.update", description: "Configure CRM pipeline stages" },
  { key: "audit.read", module: "audit", action: "read", description: "View audit logs" },
] as const;

export type PermissionKey = (typeof DEFAULT_PERMISSIONS)[number]["key"];

const permissionKeys = new Set(DEFAULT_PERMISSIONS.map((permission) => permission.key));

export function isPermissionKey(value: string): value is PermissionKey {
  return permissionKeys.has(value as PermissionKey);
}
